### ISSUE TITLE
Dependency of fastzipfile can not work on Pyhon 3.10

### ISSUE THREAD

**Issue by hk3f** [hanerx/rarCracker#3]
System: ArchLinux Linux FarchNB 5.16.3-arch1-1 #1 SMP PREEMPT Thu, 27 Jan 2022 14:18:25 +0000 x86_64 GNU/Linux
Python version: 3.10.2

pip install fastzipfile , get error for not found.

pip install local fastzipfile package , get error :
Processing ./dist/fastzipfile-2.2.tar.gz
ERROR: Package 'fastzipfile' requires a different Python: 3.10.2 not in '<3.9,>=3.5'

**Comment by hanerx** [comment]
This plugin is only work in python3.6.
If you want install it in 3.10, try replace fastzipfile plugin to standard library (may have worse performace)
https://github.com/hanerx/rarCracker/blob/40c31b55f2ff76379ec54c3611da43e949e4d432/rarCracker/main.py#L8
https://github.com/hanerx/rarCracker/blob/40c31b55f2ff76379ec54c3611da43e949e4d432/rarCracker/main.py#L26
